export { Navbar} from './layout/Navbar'
export {Home} from './layout/Home'
export {default as Post} from './Post'
export {default as Posts} from './Posts'
export {default as LogIn} from './auth/LogIn'
export {default as Register} from './auth/Register'